### ISSUE TITLE
Make tape more Ansible-ish (explained)

### ISSUE THREAD

**Issue by leonelgalan** [smashingboxes/taperole#34]
If we packaged `tape` as a ansible-galaxy role. The only two files needed on each project would be 

hosts:
```
[staging]
0.0.0.0 app_env=staging app_branch=master 
```

site.yml
```yaml
- hosts: all

  roles:
    - role: smashingboxes.tape
    tasks:
      - base
      - provision
      - deploy
    - role: roles/custom_role
```

In the future `base` could move outside of each app and used to create a snapshot (Digital Ocean) or ami (AWS) that is used to create new servers.

_tape_ as a role, will depend on other ansible-galaxy roles like: _zzet.rbenv_, _jnv.unattended-upgrades_. Other roles we haven't use that we should consider: _ANXS.postgresql_, _mivok0.users_ for creating the deploy user, etc.

The gem/executable should probably move outside of this project, to its own. Having only ruby code and doing a single `ansible-galaxy install smashingboxes.tape` (this could be done by the rails gem when installing tape into a project) to install everything it needs.

## Pros
* Two smaller repos (1: Ansible, 2: Ruby gem)
  * Reduced complexity
  * Separation of concerns: Ansible role and ruby gem
* Depend more on ansible-galaxy roles will reduce the code we have to maintain
* Follow Ansible conventions closer
